### ISSUE TITLE
Manual scrape 2022-02-01 didn't work

### ISSUE THREAD

**Issue by bbrewington** [codeforatlanta/georgia-courtbot#21]
Here's what I ran:

```
% python3 data/dekalb_scraper.py --output csv > scrape_20220201.csv
```

And output in terminal:

```
Scraping Dekalb County court cases per judicial officer...
ID	Name
282	Adams, Gregory A.
Traceback (most recent call last):
  File "data/dekalb_scraper.py", line 149, in <module>
    run(args.output)
  File "data/dekalb_scraper.py", line 123, in run
    for fields in fields_of_interest
  File "data/dekalb_scraper.py", line 123, in <listcomp>
    for fields in fields_of_interest
TypeError: unsupported operand type(s) for |: 'dict' and 'dict'
```

**Comment by abrie** [comment]
Use Python 3.9+ to resolve this error message.

Is there a requirement that we use an older version?

**Comment by BennyJW** [comment]
No requirement.  My suggestion is Google Cloud Run for automated runs of the scraping code.  Cloud Run executes docker apps, so we can just pick whatever Python image we need.
